default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nisegram_app_development

test:
  <<: *default
  database: nisegram_app_test

production:
  <<: *default
  database: nisegram_app_production
  username: nisegram_app
  password: <%= ENV['NISEGRAM_APP_DATABASE_PASSWORD'] %>